-- D1 schema: BTC recharge → credits balance (self-hosted bitcoind, server push model)
-- Apply:
--   wrangler d1 migrations apply DB --local
--   wrangler d1 migrations apply DB --remote --env production
--
-- Money precision rule: BTC is stored as integer satoshi (1 BTC = 100_000_000 sat);
-- credits/fiat are stored as integer cents. NEVER use floats for money.

-- Per-user fiat credit balance (cents). Recharge adds; purchases subtract.
ALTER TABLE users ADD COLUMN credits_cents INTEGER NOT NULL DEFAULT 0;

-- Address pool pre-generated by the wallet machine (getnewaddress) and pushed to
-- the Worker via /api/btc/pool/refill. A free address is claimed and permanently
-- bound to a user on their first recharge (one user ↔ one address).
CREATE TABLE IF NOT EXISTS btc_address_pool (
  address      TEXT PRIMARY KEY,                -- bitcoin address from the wallet
  status       TEXT NOT NULL DEFAULT 'free',    -- 'free' | 'assigned'
  user_id      TEXT,                            -- set when assigned
  created_at   INTEGER NOT NULL,                -- unix ms (push time)
  assigned_at  INTEGER                          -- unix ms
);

CREATE INDEX IF NOT EXISTS idx_btc_pool_status ON btc_address_pool(status);
-- One assigned address per user (partial unique index; NULLs allowed for free rows).
CREATE UNIQUE INDEX IF NOT EXISTS idx_btc_pool_user_unique
  ON btc_address_pool(user_id) WHERE user_id IS NOT NULL;

-- Deposit ledger. The wallet machine's detect.php pushes every receive tx; the
-- Worker resolves address→user, records the deposit, and credits the user once
-- the confirmation threshold is met (idempotent on txid+address).
CREATE TABLE IF NOT EXISTS btc_deposits (
  id                  TEXT PRIMARY KEY,         -- dep_<24hex>
  txid                TEXT NOT NULL,            -- bitcoin transaction id
  address             TEXT NOT NULL,            -- receiving address
  user_id             TEXT,                     -- resolved from pool (NULL = unknown addr)
  amount_sat          INTEGER NOT NULL,         -- integer satoshi
  confirmations       INTEGER NOT NULL DEFAULT 0,
  status              TEXT NOT NULL DEFAULT 'pending', -- 'pending' | 'credited' | 'ignored'
  rate_cents_per_btc  INTEGER,                  -- fiat rate locked at credit time
  credited_cents      INTEGER,                  -- amount added to the user's balance
  currency            TEXT NOT NULL DEFAULT 'usd',
  first_seen_at       INTEGER NOT NULL,         -- unix ms (first ingest)
  credited_at         INTEGER,                  -- unix ms (when credited)
  updated_at          INTEGER NOT NULL          -- unix ms (last ingest)
);

-- A single tx can pay multiple addresses; uniqueness is (txid, address).
CREATE UNIQUE INDEX IF NOT EXISTS idx_btc_deposits_txid_addr ON btc_deposits(txid, address);
CREATE INDEX IF NOT EXISTS idx_btc_deposits_user   ON btc_deposits(user_id);
CREATE INDEX IF NOT EXISTS idx_btc_deposits_status ON btc_deposits(status);

-- Append-only audit of every balance change (recharge +, purchase -, adjust).
CREATE TABLE IF NOT EXISTS credit_ledger (
  id                  TEXT PRIMARY KEY,         -- led_<24hex>
  user_id             TEXT NOT NULL,
  delta_cents         INTEGER NOT NULL,         -- + credit / - debit
  balance_after_cents INTEGER NOT NULL,
  reason              TEXT NOT NULL,            -- 'btc_deposit' | 'purchase' | 'adjust'
  ref                 TEXT,                     -- deposit id / order id
  created_at          INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_credit_ledger_user ON credit_ledger(user_id);
